# Generated by Django 3.1 on 2020-09-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_widget_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget_form',
            name='instructor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget_form',
            name='student_approved',
            field=models.BooleanField(default=False),
        ),
    ]
