# Generated by Django 3.1 on 2020-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200905_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget_form',
            name='approved_options',
            field=models.CharField(default='', max_length=40),
        ),
    ]
