# Generated by Django 3.1 on 2020-09-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200905_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.RemoveField(
            model_name='widget_form',
            name='approved_options',
        ),
        migrations.AddField(
            model_name='widget_form',
            name='instructor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget_form',
            name='option1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='widget_form',
            name='option1_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget_form',
            name='option2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='widget_form',
            name='option2_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget_form',
            name='option3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='widget_form',
            name='option3_approved',
            field=models.BooleanField(default=False),
        ),
    ]
