# Generated by Django 3.1 on 2020-09-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200905_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget_form',
            name='instructor_ask_to_resubmit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget_form',
            name='student_ask_to_resubmit',
            field=models.BooleanField(default=False),
        ),
    ]
