# Generated by Django 3.1 on 2020-09-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200905_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget_form',
            name='status',
            field=models.CharField(default='', max_length=40),
        ),
    ]
