# Generated by Django 3.1 on 2020-09-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20200910_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget_form',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
