# Generated by Django 3.1 on 2020-08-26 23:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200827_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 2, 12, 31, 731566)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
