# Generated by Django 3.1 on 2020-08-27 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200827_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 5, 37, 40, 285866)),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='/media/default.png', upload_to='media'),
        ),
    ]
