# Generated by Django 3.1 on 2020-08-31 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200827_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_to_display',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 13, 51, 45, 776350)),
        ),
    ]
