# Generated by Django 3.1 on 2020-08-31 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200831_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 15, 42, 25, 717304)),
        ),
    ]
