# Generated by Django 3.1 on 2020-09-05 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200905_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 17, 45, 28, 762955)),
        ),
    ]
