# Generated by Django 3.1 on 2020-09-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200911_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='level_of_study',
            new_name='what_I_want_to_talk_about',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='catch_phrase',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='intro_msg',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.AddField(
            model_name='user',
            name='catch_phrase',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='intro_msg',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
