# Generated by Django 3.1 on 2020-09-16 05:12

from django.db import migrations, models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200916_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='default.png', storage=main.storage.OverwriteStorage(), upload_to='media'),
        ),
    ]
