# Generated by Django 3.1 on 2020-09-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200916_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
