# Generated by Django 3.1 on 2020-09-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200916_0813'),
        ('main', '0019_auto_20200916_0813 copy'),
    ]

    operations = [
    ]
