# Generated by Django 3.1 on 2020-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merge_20200916_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
