# Generated by Django 3.1 on 2020-09-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200921_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
