# Generated by Django 3.1 on 2020-10-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200921_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='paypal_account',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
