# Generated by Django 3.1 on 2020-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_instructor_paypal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
